namespace PUPFMIS.Migrations.FMISMigrations
{
    using System.Data.Entity.Migrations;
    using System;
    using System.Collections.Generic;

    internal sealed class Configuration : DbMigrationsConfiguration<PUPFMIS.Models.FMISDbContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = true;
            AutomaticMigrationDataLossAllowed = true;
            MigrationsDirectory = "Migrations";
        }

        //protected override void Seed(PUPFMIS.Models.FMISDbContext context)
        //{
        //    context.AgencyDetails.AddOrUpdate(
        //        new Models.AgencyDetails { ID = 1, AccountCode = "Z006", AgencyName = "POLYTECHNIC UNIVERSITY OF THE PHILIPPINES", Address = "Anonas Street, Sta. Mesa, Manila", Region = "MAIN & NCR", OrganizationType = "STATE UNIVERSITIES AND COLLEGES", ProcurementOfficeReference = "PMO", AccountingOfficeReference = "AD", BACOfficeReference = "PMO-BACSEC", HOPEReference = "OP", PropertyOfficeReference = "PSMO" }
        //    );
        //    context.Suppliers.AddOrUpdate(
        //        new Models.Supplier { ID = 1, SupplierName = "Department of Budget and Management - Procurement Service", Address = "R.R. Road, Cristobal Street, Paco, Manila, 1007, Philippines", ContactNumber = "(02) 689 - 7750", ContactPerson = "The Manager", PurgeFlag = false, CreatedAt = DateTime.Now, Website = "www.dbm.gov.ph" },
        //        new Models.Supplier { ID = 2, SupplierName = "Supplier 1", Address = "Supplier 1 Address", ContactNumber = "(02) 689-7750", ContactPerson = "The Manager", PurgeFlag = false, CreatedAt = DateTime.Now, Website = "www.supplier1.ph" },
        //        new Models.Supplier { ID = 3, SupplierName = "Supplier 2", Address = "Supplier 2 Address", ContactNumber = "(02) 9999-9999", ContactPerson = "The Manager", PurgeFlag = false, CreatedAt = DateTime.Now, Website = null },
        //        new Models.Supplier { ID = 4, SupplierName = "Supplier 3", Address = "Supplier 3 Address", ContactNumber = "(02) 9999-9999", ContactPerson = "The Manager", PurgeFlag = false, CreatedAt = DateTime.Now, Website = null },
        //        new Models.Supplier { ID = 5, SupplierName = "Supplier 4", Address = "Supplier 4 Address", ContactNumber = "(02) 9999-9999", ContactPerson = "The Manager", PurgeFlag = false, CreatedAt = DateTime.Now, Website = "www.supplier4.com.ph" }
        //    );
        //    context.UOM.AddOrUpdate(
        //        new Models.UnitOfMeasure { ID = 1, UnitName = "Piece", Abbreviation = "PC", CreatedAt = DateTime.Now, PurgeFlag = false },
        //        new Models.UnitOfMeasure { ID = 2, UnitName = "Box", Abbreviation = "BOX", CreatedAt = DateTime.Now, PurgeFlag = false },
        //        new Models.UnitOfMeasure { ID = 3, UnitName = "Unit", Abbreviation = "UNIT", CreatedAt = DateTime.Now, PurgeFlag = false },
        //        new Models.UnitOfMeasure { ID = 4, UnitName = "Bottle", Abbreviation = "BTL", CreatedAt = DateTime.Now, PurgeFlag = false },
        //        new Models.UnitOfMeasure { ID = 5, UnitName = "Jar", Abbreviation = "JAR", CreatedAt = DateTime.Now, PurgeFlag = false },
        //        new Models.UnitOfMeasure { ID = 6, UnitName = "Cartidge", Abbreviation = "CART", CreatedAt = DateTime.Now, PurgeFlag = false },
        //        new Models.UnitOfMeasure { ID = 7, UnitName = "Ream", Abbreviation = "REAM", CreatedAt = DateTime.Now, PurgeFlag = false },
        //        new Models.UnitOfMeasure { ID = 8, UnitName = "Meter", Abbreviation = "MTR", CreatedAt = DateTime.Now, PurgeFlag = false },
        //        new Models.UnitOfMeasure { ID = 9, UnitName = "Set", Abbreviation = "SET", CreatedAt = DateTime.Now, PurgeFlag = false },
        //        new Models.UnitOfMeasure { ID = 10, UnitName = "Can", Abbreviation = "CAN", CreatedAt = DateTime.Now, PurgeFlag = false },
        //        new Models.UnitOfMeasure { ID = 11, UnitName = "Bundle", Abbreviation = "BNDL", CreatedAt = DateTime.Now, PurgeFlag = false },
        //        new Models.UnitOfMeasure { ID = 12, UnitName = "Pad", Abbreviation = "PAD", CreatedAt = DateTime.Now, PurgeFlag = false },
        //        new Models.UnitOfMeasure { ID = 13, UnitName = "Spool", Abbreviation = "SPOOL", CreatedAt = DateTime.Now, PurgeFlag = false },
        //        new Models.UnitOfMeasure { ID = 14, UnitName = "Pack", Abbreviation = "PCK", CreatedAt = DateTime.Now, PurgeFlag = false },
        //        new Models.UnitOfMeasure { ID = 15, UnitName = "Roll", Abbreviation = "ROLL", CreatedAt = DateTime.Now, PurgeFlag = false },
        //        new Models.UnitOfMeasure { ID = 16, UnitName = "Tube", Abbreviation = "TUBE", CreatedAt = DateTime.Now, PurgeFlag = false }
        //    );
        //    context.InventoryTypes.AddOrUpdate(
        //        new Models.InventoryType { ID = 1, InventoryTypeName = "Common Office Supplies", InventoryCode = "CUOS", IsTangible = true, CreatedAt = System.DateTime.Now, ResponsibilityCenter = "PSMO" },
        //        new Models.InventoryType { ID = 2, InventoryTypeName = "Inventory Items", InventoryCode = "INVT", IsTangible = true, CreatedAt = System.DateTime.Now, ResponsibilityCenter = "PSMO" },
        //        new Models.InventoryType { ID = 3, InventoryTypeName = "Machinery and Equipment", InventoryCode = "MAEQ", IsTangible = true, CreatedAt = System.DateTime.Now, ResponsibilityCenter = "FAMO" },
        //        new Models.InventoryType { ID = 4, InventoryTypeName = "Furniture, Fixtures and Books", InventoryCode = "FFBX", IsTangible = true, CreatedAt = System.DateTime.Now, ResponsibilityCenter = "FAMO" },
        //        new Models.InventoryType { ID = 5, InventoryTypeName = "Semi-Expendable Machinery and Equipment", InventoryCode = "SXME", IsTangible = true, CreatedAt = System.DateTime.Now, ResponsibilityCenter = "FAMO" },
        //        new Models.InventoryType { ID = 6, InventoryTypeName = "Semi-Expendable Funiture, Fixtures and Books", InventoryCode = "SXFB", IsTangible = true, CreatedAt = System.DateTime.Now, ResponsibilityCenter = "FAMO" },
        //        new Models.InventoryType { ID = 7, InventoryTypeName = "Services", InventoryCode = "SERV", IsTangible = false, CreatedAt = System.DateTime.Now },
        //        new Models.InventoryType { ID = 8, InventoryTypeName = "Consultancy", InventoryCode = "CONS", IsTangible = false, CreatedAt = System.DateTime.Now },
        //        new Models.InventoryType { ID = 9, InventoryTypeName = "Infrastructure", InventoryCode = "INFR", IsTangible = false, CreatedAt = System.DateTime.Now, ResponsibilityCenter = "PPDO" },
        //        new Models.InventoryType { ID = 10, InventoryTypeName = "Vehicles", InventoryCode = "VHCL", IsTangible = true, CreatedAt = System.DateTime.Now, ResponsibilityCenter = "GSO" }
        //    );

        //    context.ItemCategories.AddOrUpdate(
        //        new Models.ItemCategory { ID = 1, ItemCategoryName = "Advertising Agency Services", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 2, ItemCategoryName = "Agricultural Chemicals", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 3, ItemCategoryName = "Agricultural Machinery and Equipment", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 4, ItemCategoryName = "Agricultural Products (Seeds, Seedlings, Plants…)", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 5, ItemCategoryName = "Air-conditioning and Air-conditioning Systems", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 6, ItemCategoryName = "Air-conditioning Maintenance Services", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 7, ItemCategoryName = "Aircraft Spare Parts", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 8, ItemCategoryName = "Ammunitions and Explosives", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 9, ItemCategoryName = "Animal Feeds", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 10, ItemCategoryName = "Appliances", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 11, ItemCategoryName = "Architectural Design", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 12, ItemCategoryName = "Arts and Crafts Equipment and Accessories and Supplies", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 13, ItemCategoryName = "Audio and Visual Equipment and Supplies", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 14, ItemCategoryName = "Automation Equipment", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 15, ItemCategoryName = "Aviation Products", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 16, ItemCategoryName = "Aviation Services", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 17, ItemCategoryName = "Batteries and Cells and Accessories", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 18, ItemCategoryName = "Bedclothes, Linens and Towels", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 19, ItemCategoryName = "Beverages", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 20, ItemCategoryName = "Books, Maps and Other Publications", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 21, ItemCategoryName = "Cargo Forwarding and Hauling Services", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 22, ItemCategoryName = "Catering Services", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 23, ItemCategoryName = "Chemical Detergents", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 24, ItemCategoryName = "Chemicals and Chemical Products", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 25, ItemCategoryName = "Cleaning Equipment and Supplies", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 26, ItemCategoryName = "Color Compounds and Dispersions", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 27, ItemCategoryName = "Communication Equipment", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 28, ItemCategoryName = "Communication Equipment & Parts and Accessories", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 29, ItemCategoryName = "Computer Furniture", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 30, ItemCategoryName = "Construction Equipment", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 31, ItemCategoryName = "Construction Management Services", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 32, ItemCategoryName = "Construction Materials and Supplies", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 33, ItemCategoryName = "Construction Projects", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 34, ItemCategoryName = "Consulting Services", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 35, ItemCategoryName = "Consumer Electronics", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 36, ItemCategoryName = "Corporate Giveaways", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 37, ItemCategoryName = "Dairy Products", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 38, ItemCategoryName = "Diagnostic and Laboratory Services", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 39, ItemCategoryName = "Drugs and Medicines", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 40, ItemCategoryName = "Editorial, Design, Graphic and Fine Art Services", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 41, ItemCategoryName = "Education and Training Services", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 42, ItemCategoryName = "Educational Materials and Supplies", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 43, ItemCategoryName = "Electrical Supplies", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 44, ItemCategoryName = "Electrical Systems and Lighting Components", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 45, ItemCategoryName = "Electronic Parts and Components", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 46, ItemCategoryName = "Engineering and Laboratory Testing Equipment", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 47, ItemCategoryName = "Environmental Health/Safety Equipment", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 48, ItemCategoryName = "Equipment", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 49, ItemCategoryName = "Events Management", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 50, ItemCategoryName = "Fertilizers", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 51, ItemCategoryName = "Films", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 52, ItemCategoryName = "Financial and Insurance Services", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 53, ItemCategoryName = "Fire Fighting & Rescue and Safety Equipment", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 54, ItemCategoryName = "Fixtures", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 55, ItemCategoryName = "Flag or Accessories", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 56, ItemCategoryName = "Food Processing Equipment", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 57, ItemCategoryName = "Food Stuff", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 58, ItemCategoryName = "Freight Forwarder Services", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 59, ItemCategoryName = "Fuels/Fuel Additives & Lubricants & Anti Corrosive", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 60, ItemCategoryName = "Funeral and Associated Services", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 61, ItemCategoryName = "Furniture", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 62, ItemCategoryName = "Furniture and Furnishings", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 63, ItemCategoryName = "Furniture Parts and Accessories", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 64, ItemCategoryName = "Games and Toys", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 65, ItemCategoryName = "Gaming Equipment and Paraphernalia", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 66, ItemCategoryName = "Garments", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 67, ItemCategoryName = "General Contractor", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 68, ItemCategoryName = "General Engineering Services", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 69, ItemCategoryName = "General Merchandise", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 70, ItemCategoryName = "General Repair and Maintenance Services", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 71, ItemCategoryName = "Geotechnical Instrumentation", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 72, ItemCategoryName = "Grocery Items", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 73, ItemCategoryName = "Guns and Weapons", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 74, ItemCategoryName = "Handbook on Procurement", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 75, ItemCategoryName = "Hardware and Construction Supplies", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 76, ItemCategoryName = "Heating and Ventilation and Air Circulation", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 77, ItemCategoryName = "Helicopters - Parts", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 78, ItemCategoryName = "Horizontal Directional Drilling", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 79, ItemCategoryName = "Hospital / Medical Equipment", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 80, ItemCategoryName = "Hospital / Medical Equipment Services", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 81, ItemCategoryName = "Hotel and Lodging and Meeting Facilities", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 82, ItemCategoryName = "Hydrological Instruments", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 83, ItemCategoryName = "ICT Equipments", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 84, ItemCategoryName = "Industrial Machinery and Equipment", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 85, ItemCategoryName = "Industrial Pumps and Compressors", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 86, ItemCategoryName = "Industrial Safety Equipment", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 87, ItemCategoryName = "Information and Communication Technology (ICT) Equipment and Devices and Accessories and Peripherals", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 88, ItemCategoryName = "Information Technology", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 89, ItemCategoryName = "Institutional Food Services Equipment", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 90, ItemCategoryName = "Internet Services", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 91, ItemCategoryName = "Investigative Equipment", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 92, ItemCategoryName = "IT Broadcasting and Telecommunications", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 93, ItemCategoryName = "Janitorial Equipment", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 94, ItemCategoryName = "Janitorial Services", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 95, ItemCategoryName = "Janitorial Supplies", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 96, ItemCategoryName = "Kitchenware", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 97, ItemCategoryName = "Laboratory Supplies and Equipment", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 98, ItemCategoryName = "Laundry Services", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 99, ItemCategoryName = "Lease and Rental of Property or Building", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 100, ItemCategoryName = "Lifting Equipment and Accessories", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 101, ItemCategoryName = "Lighting and Fixtures and Accessories", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 102, ItemCategoryName = "Live Animals (Livestock, Birds, Live Fish & Etc.…)", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 103, ItemCategoryName = "Machine Tools", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 104, ItemCategoryName = "Mail and Cargo Transport Services", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 105, ItemCategoryName = "Mailing Supplies", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 106, ItemCategoryName = "Manufacturing Components and Supplies", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 107, ItemCategoryName = "Marine Transport", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 108, ItemCategoryName = "Maritime Spare Parts", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 109, ItemCategoryName = "Market Research Services", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 110, ItemCategoryName = "Measuring and Observing and Testing Equipment", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 111, ItemCategoryName = "Medical and Dental Equipment", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 112, ItemCategoryName = "Medical Supplies and Laboratory Instrument", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 113, ItemCategoryName = "Metal Fabrication", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 114, ItemCategoryName = "Meteorological Equipment and Instruments", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 115, ItemCategoryName = "Microfilm Equipment", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 116, ItemCategoryName = "Microfilm Equipment - Supplies and Accessories", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 117, ItemCategoryName = "Mining Equipment and Supplies", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 118, ItemCategoryName = "Musical Instrument Parts and Accessories", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 119, ItemCategoryName = "Musical Instruments", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 120, ItemCategoryName = "Navigation Equipment", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 121, ItemCategoryName = "Newspapers", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 122, ItemCategoryName = "Office Equipment", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 123, ItemCategoryName = "Office Equipment Parts and Accessories", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 124, ItemCategoryName = "Office Equipment Supplies and Consumables", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 125, ItemCategoryName = "Office Supplies and Devices", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 126, ItemCategoryName = "Oil/Heat Chemical Resistant Rubber", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 127, ItemCategoryName = "Ordnance Products", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 128, ItemCategoryName = "Packaging Supplies and Materials", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 129, ItemCategoryName = "Paper Materials and Products", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 130, ItemCategoryName = "Passenger Air Transportation", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 131, ItemCategoryName = "Personal Care Products", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 132, ItemCategoryName = "Pest Control Products", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 133, ItemCategoryName = "Pest Control Services", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 134, ItemCategoryName = "Pesticides or Pest Repellents", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 135, ItemCategoryName = "Photographic Equipment", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 136, ItemCategoryName = "Photographic Parts, Supplies and Accessories", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 137, ItemCategoryName = "Photography Services", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 138, ItemCategoryName = "Plastic Products", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 139, ItemCategoryName = "Power Generation and Distribution Machinery", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 140, ItemCategoryName = "Preserved or Processed Foods", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 141, ItemCategoryName = "Print and Broadcast and Aerial Advertising", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 142, ItemCategoryName = "Printed Publications", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 143, ItemCategoryName = "Printer or Facsimile or Photocopier Supplies", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 144, ItemCategoryName = "Printing Services", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 145, ItemCategoryName = "Printing Supplies", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 146, ItemCategoryName = "Public Relations Programs or Services", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 147, ItemCategoryName = "Purses, Handbags and Bags", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 148, ItemCategoryName = "Pyrotechnics and Fireworks", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 149, ItemCategoryName = "Quartermaster Items", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 150, ItemCategoryName = "Radiological/Diagnostic Equipment", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 151, ItemCategoryName = "Real Estate Development and Maintenance", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 152, ItemCategoryName = "Reproduction Services", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 153, ItemCategoryName = "Rice Milling Services", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 154, ItemCategoryName = "Safety and Occupational Products", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 155, ItemCategoryName = "Sale of Property or Building", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 156, ItemCategoryName = "Security Services", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 157, ItemCategoryName = "Security Surveillance and Detection Equipment", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 158, ItemCategoryName = "Services", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 159, ItemCategoryName = "Signage and Accessories", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 160, ItemCategoryName = "Software", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 161, ItemCategoryName = "Solvents", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 162, ItemCategoryName = "Sporting Goods", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 163, ItemCategoryName = "Structured Cabling", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 164, ItemCategoryName = "Sub-Station Contractors", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 165, ItemCategoryName = "Surveying Instruments", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 166, ItemCategoryName = "Surveying Services", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 167, ItemCategoryName = "Systems Integration", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 168, ItemCategoryName = "Telecommunications Engineering", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 169, ItemCategoryName = "Telecommunications Provider", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 170, ItemCategoryName = "Textiles", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 171, ItemCategoryName = "Timepieces and Jewelry and Gemstone Products", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 172, ItemCategoryName = "Tokens and Awards", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 173, ItemCategoryName = "Traffic Control Systems", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 174, ItemCategoryName = "Transmission and Distribution Lines", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 175, ItemCategoryName = "Transportation and Communications Services", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 176, ItemCategoryName = "Travel, Food, Lodging and Entertainment Services", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 177, ItemCategoryName = "Vehicle Parts and Accessories", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 178, ItemCategoryName = "Vehicle Repair and Maintenance", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 179, ItemCategoryName = "Vehicles", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 180, ItemCategoryName = "Veterinary Products and Supplies", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 181, ItemCategoryName = "Video Production Services", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 182, ItemCategoryName = "Waste Management and Recycling", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 183, ItemCategoryName = "Water and Waste Water Treatment Supply & Disposal", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 184, ItemCategoryName = "Water Service Connection Materials/Fittings", PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.ItemCategory { ID = 185, ItemCategoryName = "Well Drilling and Construction Services", PurgeFlag = false, CreatedAt = DateTime.Now }
        //    );

        //    context.SystemVariables.AddOrUpdate(
        //        new Models.SystemVariables { ID = 1, VariableName = "Inflation Rate", Value = "5"}
        //    );
        //    context.Roles.AddOrUpdate(
        //        new Models.Roles { ID = 1, Role = "Super User" },
        //        new Models.Roles { ID = 2, Role = "System Administrator" },
        //        new Models.Roles { ID = 3, Role = "End-User" },
        //        new Models.Roles { ID = 4, Role = "Procurement Administrator" },
        //        new Models.Roles { ID = 5, Role = "Property Administrator" },
        //        new Models.Roles { ID = 6, Role = "Supplies Administrator" },
        //        new Models.Roles { ID = 7, Role = "Warehouse Administrator" },
        //        new Models.Roles { ID = 8, Role = "Supplies Officer" },
        //        new Models.Roles { ID = 9, Role = "Budget Administrator" },
        //        new Models.Roles { ID = 10, Role = "Budget Officer" }
        //    );
        //    context.PPMPDeadlines.AddOrUpdate(
        //        new Models.PPMPDeadlines { ID = 1, FiscalYear = "2021", StartDate = DateTime.Now, ClosingDate = DateTime.Now, CreatedAt = DateTime.Now, PurgeFlag = false, Status = "Open" },
        //        new Models.PPMPDeadlines { ID = 2, FiscalYear = "2022", StartDate = DateTime.Now, ClosingDate = DateTime.Now, CreatedAt = DateTime.Now, PurgeFlag = false, Status = "Open" }
        //    );

        //    context.UserAccounts.AddOrUpdate(
        //        new Models.UserAccounts { ID = 1, EmpCode = "2011-0111", Email = "ajbablir@pup.edu.ph", DepartmentCode = "ICTO", RoleReference = 1, PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.UserAccounts { ID = 2, EmpCode = "2000-00089", Email = "ecsalao@pup.edu.ph", DepartmentCode = "PMO", RoleReference = 4, PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.UserAccounts { ID = 3, EmpCode = "2014-01123", Email = "jctpasumbal@pup.edu.ph", DepartmentCode = "CCIS", RoleReference = 3, PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.UserAccounts { ID = 4, EmpCode = "2014-01124", Email = "jmotestor@pup.edu.ph", DepartmentCode = "CCIS-LAB", RoleReference = 3, PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.UserAccounts { ID = 5, EmpCode = "1998-00136", Email = "afperez@pup.edu.ph", DepartmentCode = "BSO-BOS", RoleReference = 10, PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.UserAccounts { ID = 6, EmpCode = "2014-00090", Email = "sbcruz@pup.edu.ph", DepartmentCode = "OUR", RoleReference = 10, PurgeFlag = false, CreatedAt = DateTime.Now },
        //        new Models.UserAccounts { ID = 7, EmpCode = "1998-00139", Email = "op@pup.edu.ph", DepartmentCode = "OP", RoleReference = 10, PurgeFlag = false, CreatedAt = DateTime.Now }
        //    );

        //    context.ProcurementModes.AddOrUpdate(
        //        new Models.ModeOfProcurement { ID = 1, ModeOfProcurementName = "Competitive Bidding", CreatedAt = DateTime.Now },
        //        new Models.ModeOfProcurement { ID = 2, ModeOfProcurementName = "Limited Source Bidding", CreatedAt = DateTime.Now },
        //        new Models.ModeOfProcurement { ID = 3, ModeOfProcurementName = "Direct Contracting", CreatedAt = DateTime.Now },
        //        new Models.ModeOfProcurement { ID = 4, ModeOfProcurementName = "Repeat Order", CreatedAt = DateTime.Now },
        //        new Models.ModeOfProcurement { ID = 5, ModeOfProcurementName = "Shopping", CreatedAt = DateTime.Now },
        //        new Models.ModeOfProcurement { ID = 6, ModeOfProcurementName = "NP-53.1 Two Failed Biddings", CreatedAt = DateTime.Now },
        //        new Models.ModeOfProcurement { ID = 7, ModeOfProcurementName = "NP-53.2 Emergency Cases", CreatedAt = DateTime.Now },
        //        new Models.ModeOfProcurement { ID = 8, ModeOfProcurementName = "NP-53.3 Take-Over of Contracts", CreatedAt = DateTime.Now },
        //        new Models.ModeOfProcurement { ID = 9, ModeOfProcurementName = "NP-53.4 Adjacent or Contiguous", CreatedAt = DateTime.Now },
        //        new Models.ModeOfProcurement { ID = 10, ModeOfProcurementName = "NP-53.5 Agency-to-Agency", CreatedAt = DateTime.Now },
        //        new Models.ModeOfProcurement { ID = 11, ModeOfProcurementName = "NP-53.6 Scientific, Scholarly, Artistic Work, Exclusive Technology and Media Services", CreatedAt = DateTime.Now },
        //        new Models.ModeOfProcurement { ID = 12, ModeOfProcurementName = "NP-53.7 Highly Technical Consultants", CreatedAt = DateTime.Now },
        //        new Models.ModeOfProcurement { ID = 13, ModeOfProcurementName = "NP-53.8 Defense Cooperation Agreement", CreatedAt = DateTime.Now },
        //        new Models.ModeOfProcurement { ID = 14, ModeOfProcurementName = "NP-53.9 - Small Value Procurement", CreatedAt = DateTime.Now },
        //        new Models.ModeOfProcurement { ID = 15, ModeOfProcurementName = "NP-53.10 Lease of Real Property and Venue", CreatedAt = DateTime.Now },
        //        new Models.ModeOfProcurement { ID = 16, ModeOfProcurementName = "NP-53.11 NGO Participation", CreatedAt = DateTime.Now },
        //        new Models.ModeOfProcurement { ID = 17, ModeOfProcurementName = "NP-53.12 Community Participation", CreatedAt = DateTime.Now },
        //        new Models.ModeOfProcurement { ID = 18, ModeOfProcurementName = "NP-53.13 UN Agencies, Int'l Organizations or International Financing Institutions", CreatedAt = DateTime.Now },
        //        new Models.ModeOfProcurement { ID = 18, ModeOfProcurementName = "Others - Foreign-funded Procurement", CreatedAt = DateTime.Now }
        //    );
        //}
    }
}
