namespace PUPFMIS.Migrations.FMISMigrations
{
    using System.Data.Entity.Migrations;
    using System;

    internal sealed class Configuration : DbMigrationsConfiguration<PUPFMIS.Models.FMISDbContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = true;
            AutomaticMigrationDataLossAllowed = true;
            MigrationsDirectory = "Migrations";
        }

        protected override void Seed(PUPFMIS.Models.FMISDbContext context)
        {
            context.Suppliers.AddOrUpdate(
                new Models.Supplier { ID = 1, SupplierName = "Department of Budget and Management - Procurement Service", Address = "R.R. Road, Cristobal Street, Paco, Manila, 1007, Philippines", ContactNumber = "(02) 689 - 7750", ContactPerson = "The Manager", PurgeFlag = false, CreatedAt = DateTime.Now, Website = "www.dbm.gov.ph" }
            );
            context.UOM.AddOrUpdate(
                new Models.UnitOfMeasure { ID = 1, UnitName = "Piece", Abbreviation = "PC", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.UnitOfMeasure { ID = 2, UnitName = "Box", Abbreviation = "BOX", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.UnitOfMeasure { ID = 3, UnitName = "Unit", Abbreviation = "UNIT", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.UnitOfMeasure { ID = 4, UnitName = "Bottle", Abbreviation = "BTL", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.UnitOfMeasure { ID = 5, UnitName = "Jar", Abbreviation = "JAR", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.UnitOfMeasure { ID = 6, UnitName = "Cartidge", Abbreviation = "CART", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.UnitOfMeasure { ID = 7, UnitName = "Ream", Abbreviation = "REAM", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.UnitOfMeasure { ID = 8, UnitName = "Meter", Abbreviation = "MTR", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.UnitOfMeasure { ID = 9, UnitName = "Set", Abbreviation = "SET", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.UnitOfMeasure { ID = 10, UnitName = "Can", Abbreviation = "CAN", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.UnitOfMeasure { ID = 11, UnitName = "Bundle", Abbreviation = "BNDL", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.UnitOfMeasure { ID = 12, UnitName = "Pad", Abbreviation = "PAD", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.UnitOfMeasure { ID = 13, UnitName = "Spool", Abbreviation = "SPOOL", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.UnitOfMeasure { ID = 14, UnitName = "Pack", Abbreviation = "PCK", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.UnitOfMeasure { ID = 15, UnitName = "Roll", Abbreviation = "ROLL", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.UnitOfMeasure { ID = 16, UnitName = "Tube", Abbreviation = "TUBE", CreatedAt = DateTime.Now, PurgeFlag = false }
            );
            context.InventoryTypes.AddOrUpdate(
                new Models.InventoryType { ID = 1, InventoryTypeName = "Common Use Office Supplies", InventoryCode = "CUOS", IsTangible = true, CreatedAt = System.DateTime.Now },
                new Models.InventoryType { ID = 2, InventoryTypeName = "Machinery and Equipment", InventoryCode = "MAEQ", IsTangible = true, CreatedAt = System.DateTime.Now },
                new Models.InventoryType { ID = 3, InventoryTypeName = "Furniture, Fixtures and Books", InventoryCode = "FFBX", IsTangible = true, CreatedAt = System.DateTime.Now },
                new Models.InventoryType { ID = 4, InventoryTypeName = "Semi-Expendable Machinery and Equipment", InventoryCode = "SXME", IsTangible = true, CreatedAt = System.DateTime.Now },
                new Models.InventoryType { ID = 5, InventoryTypeName = "Semi-Expendable Funiture, Fixtures and Books", InventoryCode = "SXFB", IsTangible = true, CreatedAt = System.DateTime.Now },
                new Models.InventoryType { ID = 6, InventoryTypeName = "Services", InventoryCode = "SERV", IsTangible = false, CreatedAt = System.DateTime.Now },
                new Models.InventoryType { ID = 7, InventoryTypeName = "Consultancy", InventoryCode = "CONS", IsTangible = false, CreatedAt = System.DateTime.Now },
                new Models.InventoryType { ID = 8, InventoryTypeName = "Infrastructure", InventoryCode = "INFR", IsTangible = false, CreatedAt = System.DateTime.Now }
            );
            context.DBMCategories.AddOrUpdate(
                new Models.DBMCategories { ID = 1, ItemCategoryName = "Common Electrical Supplies", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.DBMCategories { ID = 2, ItemCategoryName = "Common Office Supplies", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.DBMCategories { ID = 3, ItemCategoryName = "Common Office Devices", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.DBMCategories { ID = 4, ItemCategoryName = "Common Janitorial Supplies", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.DBMCategories { ID = 5, ItemCategoryName = "Common Office Equipment", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.DBMCategories { ID = 6, ItemCategoryName = "Common Computer Supplies", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.DBMCategories { ID = 7, ItemCategoryName = "Handbook on Procurement", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.DBMCategories { ID = 8, ItemCategoryName = "Consumables", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.DBMCategories { ID = 9, ItemCategoryName = "Equipment", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.DBMCategories { ID = 10, ItemCategoryName = "Pesticides or Pest Repellents", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.DBMCategories { ID = 11, ItemCategoryName = "Solvents", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.DBMCategories { ID = 12, ItemCategoryName = "Color Compounds and Dispersions", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.DBMCategories { ID = 13, ItemCategoryName = "Films", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.DBMCategories { ID = 14, ItemCategoryName = "Paper Materials and Products", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.DBMCategories { ID = 15, ItemCategoryName = "Batteries and Cells and Accessories", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.DBMCategories { ID = 16, ItemCategoryName = "Manufacturing Components and Supplies", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.DBMCategories { ID = 17, ItemCategoryName = "Heating and Ventilation and Air Circulation", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.DBMCategories { ID = 18, ItemCategoryName = "Lighting and Fixtures and Accessories", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.DBMCategories { ID = 19, ItemCategoryName = "Measuring and Observing and Testing Equipment", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.DBMCategories { ID = 20, ItemCategoryName = "Cleaning Equipment and Supplies", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.DBMCategories { ID = 21, ItemCategoryName = "Information and Communication Technology (ICT) Equipment and Devices and Accessories", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.DBMCategories { ID = 22, ItemCategoryName = "Office Equipment and Accessories and Supplies", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.DBMCategories { ID = 23, ItemCategoryName = "Printer or Facsimile or Photocopier Supplies", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.DBMCategories { ID = 24, ItemCategoryName = "Audio and Visual Equipment and Supplies", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.DBMCategories { ID = 25, ItemCategoryName = "Flag or Accessories", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.DBMCategories { ID = 26, ItemCategoryName = "Printed Publications", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.DBMCategories { ID = 27, ItemCategoryName = "Fire Fighting Equipment", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.DBMCategories { ID = 28, ItemCategoryName = "Consumer Electronics", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.DBMCategories { ID = 29, ItemCategoryName = "Furniture and Furnishings", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.DBMCategories { ID = 30, ItemCategoryName = "Arts and Crafts Equipment and Accessories and Supplies", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.DBMCategories { ID = 31, ItemCategoryName = "Software", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.DBMCategories { ID = 32, ItemCategoryName = "Passenger Air Transportation", CreatedAt = DateTime.Now, PurgeFlag = false }
            );
            context.PhilGEPSCategories.AddOrUpdate(
                new Models.PhilGEPSCategories { ID = 1, ItemCategoryName = "Advertising Agency Services", CategoryFor = "Services", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 2, ItemCategoryName = "Agricultural Chemicals", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 3, ItemCategoryName = "Agricultural Machinery and Equipment", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 4, ItemCategoryName = "Agricultural Products (Seeds, Seedlings, Plants…)", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 5, ItemCategoryName = "Air-conditioning and Air-conditioning Systems", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 6, ItemCategoryName = "Air-conditioning Maintenance Services", CategoryFor = "Services", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 7, ItemCategoryName = "Aircraft Spare Parts", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 8, ItemCategoryName = "Ammunitions and Explosives", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 9, ItemCategoryName = "Animal Feeds", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 10, ItemCategoryName = "Appliances", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 11, ItemCategoryName = "Architectural Design", CategoryFor = "Services", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 12, ItemCategoryName = "Arts And Crafts Accessories and Supplies", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 13, ItemCategoryName = "Audio and Visual Equipment", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 14, ItemCategoryName = "Automation Equipment", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 15, ItemCategoryName = "Aviation Products", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 16, ItemCategoryName = "Aviation Services", CategoryFor = "Services", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 17, ItemCategoryName = "Bedclothes, Linens and Towels", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 18, ItemCategoryName = "Beverages", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 19, ItemCategoryName = "Books, Maps and Other Publications", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 20, ItemCategoryName = "Cargo Forwarding and Hauling Services", CategoryFor = "Services", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 21, ItemCategoryName = "Catering Services", CategoryFor = "Services", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 22, ItemCategoryName = "Chemical Detergents", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 23, ItemCategoryName = "Chemicals and Chemical Products", CategoryFor = "Services", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 24, ItemCategoryName = "Communication Equipment", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 25, ItemCategoryName = "Communication Equipment & Parts and Accessories", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 26, ItemCategoryName = "Computer Furniture", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 27, ItemCategoryName = "Construction Equipment", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 28, ItemCategoryName = "Construction Management Services", CategoryFor = "Services", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 29, ItemCategoryName = "Construction Materials and Supplies", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 30, ItemCategoryName = "Construction Projects", CategoryFor = "Services", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 31, ItemCategoryName = "Consulting Services", CategoryFor = "Services", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 32, ItemCategoryName = "Corporate Giveaways", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 33, ItemCategoryName = "Dairy Products", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 34, ItemCategoryName = "Diagnostic and Laboratory Services", CategoryFor = "Services", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 35, ItemCategoryName = "Drugs and Medicines", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 36, ItemCategoryName = "Editorial, Design, Graphic and Fine Art Services", CategoryFor = "Services", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 37, ItemCategoryName = "Education and Training Services", CategoryFor = "Services", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 38, ItemCategoryName = "Educational Materials and Supplies", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 39, ItemCategoryName = "Electrical Supplies", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 40, ItemCategoryName = "Electrical Systems and Lighting Components", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 41, ItemCategoryName = "Electronic Parts and Components", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 42, ItemCategoryName = "Engineering and Laboratory Testing Equipment", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 43, ItemCategoryName = "Environmental Health/Safety Equipment", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 44, ItemCategoryName = "Events Management", CategoryFor = "Services", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 45, ItemCategoryName = "Fertilizers", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 46, ItemCategoryName = "Financial and Insurance Services", CategoryFor = "Services", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 47, ItemCategoryName = "Fire Fighting & Rescue and Safety Equipment", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 48, ItemCategoryName = "Fixtures", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 49, ItemCategoryName = "Flags", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 50, ItemCategoryName = "Food Processing Equipment", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 51, ItemCategoryName = "Food Stuff", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 52, ItemCategoryName = "Freight Forwarder Services", CategoryFor = "Services", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 53, ItemCategoryName = "Fuels/Fuel Additives & Lubricants & Anti Corrosive", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 54, ItemCategoryName = "Funeral and Associated Services", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 55, ItemCategoryName = "Furniture", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 56, ItemCategoryName = "Furniture Parts and Accessories", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 57, ItemCategoryName = "Games and Toys", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 58, ItemCategoryName = "Gaming Equipment and Paraphernalia", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 59, ItemCategoryName = "Garments", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 60, ItemCategoryName = "General Contractor", CategoryFor = "Services", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 61, ItemCategoryName = "General Engineering Services", CategoryFor = "Services", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 62, ItemCategoryName = "General Merchandise", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 63, ItemCategoryName = "General Repair and Maintenance Services", CategoryFor = "Services", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 64, ItemCategoryName = "Geotechnical Instrumentation", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 65, ItemCategoryName = "Grocery Items", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 66, ItemCategoryName = "Guns and Weapons", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 67, ItemCategoryName = "Hardware and Construction Supplies", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 68, ItemCategoryName = "Helicopters - Parts", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 69, ItemCategoryName = "Horizontal Directional Drilling", CategoryFor = "Services", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 70, ItemCategoryName = "Hospital / Medical Equipment", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 71, ItemCategoryName = "Hospital / Medical Equipment Services", CategoryFor = "Services", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 72, ItemCategoryName = "Hotel and Lodging and Meeting Facilities", CategoryFor = "Services", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 73, ItemCategoryName = "Hydrological Instruments", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 74, ItemCategoryName = "Industrial Machinery and Equipment", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 75, ItemCategoryName = "Industrial Pumps and Compressors", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 76, ItemCategoryName = "Industrial Safety Equipment", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 77, ItemCategoryName = "Information Technology", CategoryFor = "Services", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 78, ItemCategoryName = "Information Technology Parts & Accessories & Peripherals", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 79, ItemCategoryName = "Institutional Food Services Equipment", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 80, ItemCategoryName = "Internet Services", CategoryFor = "Services", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 81, ItemCategoryName = "Investigative Equipment", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 82, ItemCategoryName = "IT Broadcasting and Telecommunications", CategoryFor = "Services", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 83, ItemCategoryName = "Janitorial Equipment", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 84, ItemCategoryName = "Janitorial Services", CategoryFor = "Services", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 85, ItemCategoryName = "Janitorial Supplies", CategoryFor = "Serives", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 86, ItemCategoryName = "Kitchenware", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 87, ItemCategoryName = "Laboratory Supplies and Equipment", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 88, ItemCategoryName = "Laundry Services", CategoryFor = "Services", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 89, ItemCategoryName = "Lease and Rental of Property or Building", CategoryFor = "Services", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 90, ItemCategoryName = "Lifting Equipment and Accessories", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 91, ItemCategoryName = "Live Animals (Livestock, Birds, Live Fish & Etc.…)", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 92, ItemCategoryName = "Machine Tools", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 93, ItemCategoryName = "Mail and Cargo Transport Services", CategoryFor = "Service", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 94, ItemCategoryName = "Mailing Supplies", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 95, ItemCategoryName = "Marine Transport", CategoryFor = "Services", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 96, ItemCategoryName = "Maritime Spare Parts", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 97, ItemCategoryName = "Market Research Services", CategoryFor = "Services", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 98, ItemCategoryName = "Medical and Dental Equipment", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 99, ItemCategoryName = "Medical Supplies and Laboratory Instrument", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 100, ItemCategoryName = "Metal Fabrication", CategoryFor = "Services", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 101, ItemCategoryName = "Meteorological Equipment and Instruments", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 102, ItemCategoryName = "Microfilm Equipment", CategoryFor = "Item", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 103, ItemCategoryName = "Microfilm Equipment - Supplies and Accessories", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 104, ItemCategoryName = "Mining Equipment and Supplies", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 105, ItemCategoryName = "Musical Instrument Parts and Accessories", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 106, ItemCategoryName = "Musical Instruments", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 107, ItemCategoryName = "Navigation Equipment", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 108, ItemCategoryName = "Newspapers", CategoryFor = "Services", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 109, ItemCategoryName = "Office Equipment", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 110, ItemCategoryName = "Office Equipment Parts and Accessories", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 111, ItemCategoryName = "Office Equipment Supplies and Consumables", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 112, ItemCategoryName = "Office Supplies and Devices", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 113, ItemCategoryName = "Oil/Heat Chemical Resistant Rubber", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 114, ItemCategoryName = "Ordnance Products", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 115, ItemCategoryName = "Packaging Supplies and Materials", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 116, ItemCategoryName = "Personal Care Products", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 117, ItemCategoryName = "Pest Control Products", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 118, ItemCategoryName = "Pest Control Services", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 119, ItemCategoryName = "Photographic Equipment", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 120, ItemCategoryName = "Photographic Parts, Supplies and Accessories", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 121, ItemCategoryName = "Photography Services", CategoryFor = "Services", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 122, ItemCategoryName = "Plastic Products", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 123, ItemCategoryName = "Power Generation and Distribution Machinery", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 124, ItemCategoryName = "Preserved or Processed Foods", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 125, ItemCategoryName = "Print and Broadcast and Aerial Advertising", CategoryFor = "Services", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 126, ItemCategoryName = "Printing Services", CategoryFor = "Services", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 127, ItemCategoryName = "Printing Supplies", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 128, ItemCategoryName = "Public Relations Programs or Services", CategoryFor = "Services", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 129, ItemCategoryName = "Purses, Handbags and Bags", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 130, ItemCategoryName = "Pyrotechnics and Fireworks", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 131, ItemCategoryName = "Quartermaster Items", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 132, ItemCategoryName = "Radiological/Diagnostic Equipment", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 133, ItemCategoryName = "Real Estate Development and Maintenance", CategoryFor = "Services", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 134, ItemCategoryName = "Reproduction Services", CategoryFor = "Services", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 135, ItemCategoryName = "Rice Milling Services", CategoryFor = "Services", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 136, ItemCategoryName = "Safety and Occupational Products", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 137, ItemCategoryName = "Sale of Property or Building", CategoryFor = "Services", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 138, ItemCategoryName = "Security Services", CategoryFor = "Services", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 139, ItemCategoryName = "Security Surveillance and Detection Equipment", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 140, ItemCategoryName = "Services", CategoryFor = "Services", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 141, ItemCategoryName = "Signage and Accessories", CategoryFor = "Services", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 142, ItemCategoryName = "Sporting Goods", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 143, ItemCategoryName = "Structured Cabling", CategoryFor = "Services", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 144, ItemCategoryName = "Sub-Station Contractors", CategoryFor = "Services", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 145, ItemCategoryName = "Surveying Instruments", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 146, ItemCategoryName = "Surveying Services", CategoryFor = "Services", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 147, ItemCategoryName = "Systems Integration", CategoryFor = "Services", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 148, ItemCategoryName = "Telecommunications Engineering", CategoryFor = "Services", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 149, ItemCategoryName = "Telecommunications Provider", CategoryFor = "Services", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 150, ItemCategoryName = "Textiles", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 151, ItemCategoryName = "Timepieces and Jewelry and Gemstone Products", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 152, ItemCategoryName = "Tokens and Awards", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 153, ItemCategoryName = "Traffic Control Systems", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 154, ItemCategoryName = "Transmission and Distribution Lines", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 155, ItemCategoryName = "Transportation and Communications Services", CategoryFor = "Services", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 156, ItemCategoryName = "Travel, Food, Lodging and Entertainment Services", CategoryFor = "Services", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 157, ItemCategoryName = "Vehicle Parts and Accessories", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 158, ItemCategoryName = "Vehicle Repair and Maintenance", CategoryFor = "Services", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 159, ItemCategoryName = "Vehicles", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 160, ItemCategoryName = "Veterinary Products and Supplies", CategoryFor = "Items", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 161, ItemCategoryName = "Video Production Services", CategoryFor = "Services", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 162, ItemCategoryName = "Waste Management and Recycling", CategoryFor = "Services", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 163, ItemCategoryName = "Water and Waste Water Treatment Supply & Disposal", CategoryFor = "Services", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 164, ItemCategoryName = "Water Service Connection Materials/Fittings", CategoryFor = "Service", CreatedAt = DateTime.Now, PurgeFlag = false },
                new Models.PhilGEPSCategories { ID = 165, ItemCategoryName = "Well Drilling and Construction Services", CategoryFor = "Services", CreatedAt = DateTime.Now, PurgeFlag = false }
            );
            context.SystemVariables.AddOrUpdate(
                new Models.SystemVariables { ID = 1, VariableName = "Inflation Rate", Value = "5"}
            );
            context.Roles.AddOrUpdate(
                new Models.Roles { ID = 1, Role = "Super User" },
                new Models.Roles { ID = 2, Role = "System Administrator" },
                new Models.Roles { ID = 3, Role = "Procurement Administrator" },
                new Models.Roles { ID = 4, Role = "Property Administrator" },
                new Models.Roles { ID = 5, Role = "Supplies Administrator" },
                new Models.Roles { ID = 6, Role = "Warehouse Administrator" },
                new Models.Roles { ID = 7, Role = "Supplies Officer" },
                new Models.Roles { ID = 8, Role = "Budget Administrator" },
                new Models.Roles { ID = 9, Role = "Budget Officer" }
            );
            context.PPMPDeadlines.AddOrUpdate(
                new Models.PPMPDeadlines { ID = 1, FiscalYear = "2021", StartDate = DateTime.Now, ClosingDate = DateTime.Now, CreatedAt = DateTime.Now, PurgeFlag = false, Status = "Open" },
                new Models.PPMPDeadlines { ID = 2, FiscalYear = "2022", StartDate = DateTime.Now, ClosingDate = DateTime.Now, CreatedAt = DateTime.Now, PurgeFlag = false, Status = "Open" }
            );

            context.Items.AddOrUpdate(
                new Models.Item {
                    ID  = 1,
                    ItemCode = "01-011-001",
                    ItemName = "Alcohol",
                    ItemShortSpecifications = "Ethyl, 500ml",
                    ItemSpecifications = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                    ProcurementSource = Models.ProcurementSources.PS_DBM,
                    InventoryTypeReference = 1, 
                    ItemCategoryReference =  11,
                    AccountClass = "5020301000",
                    ItemImage =  null,
                    PackagingUOMReference = 2,
                    IndividualUOMReference = 4,
                    DistributionQtyPerPack = 36,
                    MinimumIssuanceQty = 1,
                    PurgeFlag =  false,
                    CreatedAt = DateTime.Now
                },
                new Models.Item
                {
                    ID = 2,
                    ItemCode = "01-014-001",
                    ItemName = "Paper",
                    ItemShortSpecifications = "80gsm, 8.5\" x 11\" (SHORT)",
                    ItemSpecifications = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                    ProcurementSource = Models.ProcurementSources.PS_DBM,
                    InventoryTypeReference = 1,
                    ItemCategoryReference = 14,
                    AccountClass = "5020301000",
                    ItemImage = null,
                    PackagingUOMReference = 2,
                    IndividualUOMReference = 7,
                    DistributionQtyPerPack = 5,
                    MinimumIssuanceQty = 1,
                    PurgeFlag = false,
                    CreatedAt = DateTime.Now
                },
                new Models.Item
                {
                    ID = 3,
                    ItemCode = "02-021-001",
                    ItemName = "Desktop Computer",
                    ItemShortSpecifications = "Mithi Desktop Computer, Acer Veriton M2640G",
                    ItemSpecifications = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                    ProcurementSource = Models.ProcurementSources.PS_DBM,
                    InventoryTypeReference = 2,
                    ItemCategoryReference = 21,
                    AccountClass = "5020301000",
                    ItemImage = null,
                    PackagingUOMReference = 3,
                    IndividualUOMReference = 3,
                    DistributionQtyPerPack = 1,
                    MinimumIssuanceQty = 1,
                    PurgeFlag = false,
                    CreatedAt = DateTime.Now
                },
                new Models.Item
                {
                    ID = 4,
                    ItemCode = "01-030-001",
                    ItemName = "Toilet Tissue Paper",
                    ItemShortSpecifications = "2-ply",
                    ItemSpecifications = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                    ProcurementSource = Models.ProcurementSources.PS_DBM,
                    InventoryTypeReference = 1,
                    ItemCategoryReference = 30,
                    AccountClass = "5020301000",
                    ItemImage = null,
                    PackagingUOMReference = 14,
                    IndividualUOMReference = 15,
                    DistributionQtyPerPack = 12,
                    MinimumIssuanceQty = 5,
                    PurgeFlag = false,
                    CreatedAt = DateTime.Now
                },
                new Models.Item
                {
                    ID = 5,
                    ItemCode = "04-021-004",
                    ItemName = "Printer",
                    ItemShortSpecifications = "Inkjet, 4-in-1 Network Printer",
                    ItemSpecifications = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                    ProcurementSource = Models.ProcurementSources.Non_DBM,
                    InventoryTypeReference = 4,
                    ItemCategoryReference = 30,
                    AccountClass = "5020301000",
                    ItemImage = null,
                    PackagingUOMReference = 3,
                    IndividualUOMReference = 3,
                    DistributionQtyPerPack = 1,
                    MinimumIssuanceQty = 1,
                    PurgeFlag = false,
                    CreatedAt = DateTime.Now
                }
            );
            context.ItemPrices.AddOrUpdate(
                new Models.ItemPrice { ID = 1, Item = 1, UnitPrice = 73.20m, IsPrevailingPrice = true, EffectivityDate = DateTime.Now, CreatedAt = DateTime.Now },
                new Models.ItemPrice { ID = 2, Item = 2, UnitPrice = 180.50m, IsPrevailingPrice = true, EffectivityDate = DateTime.Now, CreatedAt = DateTime.Now },
                new Models.ItemPrice { ID = 3, Item = 3, UnitPrice = 40000.00m, IsPrevailingPrice = true, EffectivityDate = DateTime.Now, CreatedAt = DateTime.Now },
                new Models.ItemPrice { ID = 4, Item = 4, UnitPrice = 150.00m, IsPrevailingPrice = true, EffectivityDate = DateTime.Now, CreatedAt = DateTime.Now }
            );
            context.Services.AddOrUpdate(
                new Models.Services
                {
                    ID = 1,
                    ServiceCode = "06-001-001",
                    ServiceName = "Blueprint Design",
                    ItemShortSpecifications = "Designing of Blueprint for construction projects",
                    ServiceTypeReference = 6,
                    ServiceCategoryReference = 1,
                    ProcurementSource = Models.ProcurementSources.Non_DBM,
                    AccountClass = "5020399000",
                    PurgeFlag = false,
                    CreatedAt = DateTime.Now
                },
                new Models.Services
                {
                    ID = 1,
                    ServiceCode = "06-149-002",
                    ServiceName = "Installation of Network with Internet Connectivity",
                    ItemShortSpecifications = "Procurement and Installation of Internet Connection with network",
                    ServiceTypeReference = 6,
                    ServiceCategoryReference = 149,
                    ProcurementSource = Models.ProcurementSources.Non_DBM,
                    AccountClass = "5020499000",
                    PurgeFlag = false,
                    CreatedAt = DateTime.Now
                },
                new Models.Services
                {
                    ID = 1,
                    ServiceCode = "06-001-003",
                    ServiceName = "Advertising Services (Print)",
                    ItemShortSpecifications = "Advertising Services for Print Media",
                    ServiceTypeReference = 6,
                    ServiceCategoryReference = 1,
                    ProcurementSource = Models.ProcurementSources.Non_DBM,
                    AccountClass = "5020501000",
                    PurgeFlag = false,
                    CreatedAt = DateTime.Now
                }
            );
        }
    }
}
